//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apples_To_Apples
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerInfo : GameInfo
    {
        public int PlayerNumber { get; set; }
        public string AwesomePoints { get; set; }
        public string Choice { get; set; }
    }
}
